spring.application.name=inventory-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory-service
spring.datasource.username=postgres
spring.datasource.password=root@123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=0

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# KAFKA
# REMOVE EVERYTHING ELSE. JUST THESE THREE:
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=inventory-service-group-v4
#spring.kafka.consumer.auto-offset-reset=earliest

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=DEBUG